'use strict';

/**
 * discovery.js — which Strapi content types the Relations tab works with,
 * and which of their fields are relations.
 *
 * This used to be entirely live: probe candidate plural routes, sample
 * entries, infer relation-shaped fields by sniffing populated values. That
 * approach worked but was necessarily approximate (see git history / the
 * 2026-08-10 design doc) — it could miss a field that happened to be empty
 * in every sample, and had no way to know a relation's exact TARGET content
 * type, only a name-based guess.
 *
 * `schema-registry.json` replaces the guessing with ground truth: it's
 * generated by `scripts/generate-relation-schema.js` directly from Strapi's
 * own `schema.json` files in the `cancerfax-strapi-backend` repo, which
 * states a relation's field name, cardinality, and exact target type
 * explicitly — nothing to infer. Regenerate it when the backend schema
 * changes; this module just reads the committed result.
 *
 * What's still live: `discoverContentTypes()` still calls prod for each
 * registered type's current entry count and to confirm the route is still
 * reachable — the registry can go stale (a type renamed or removed since it
 * was generated), and this is what catches that rather than silently
 * trusting a snapshot forever.
 */

const { API_BASE } = require('../resources/shared');
const { strapiRequest } = require('../resources/strapi-client');
const REGISTRY = require('./schema-registry.json');

/**
 * Relation fields already governed by another feature in this app —
 * surfaced as "current relations" like any other, but never offered as a
 * write target here, so the Relations tab can't fight the Resources tab's
 * classifier over the same field.
 */
const RESERVED_RELATION_FIELDS = new Set(['resource_category', 'resource_subcategory', 'resource_tags']);

/** A Strapi relation's populated shape: `{ documentId, ... }`, singular or (for a many relation) an array of these. Still needed by shared.js to tell a relation subtree apart from prose when flattening entry text. */
function isRelationEntry(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value) && typeof value.documentId === 'string';
}

/** Media/upload fields are ALSO `{ documentId, url, ... }` objects in Strapi v5 — files are content-managed too. Distinguishing them still matters for text-flattening (shared.js must not treat a populated image field as a relation subtree OR walk into its binary metadata as if it were prose). */
function isMediaEntry(value) {
  return isRelationEntry(value) && typeof value.url === 'string' && (value.mime || value.ext || value.provider);
}

function isRelationValue(value) {
  if (Array.isArray(value)) {
    return value.length > 0 && value.every((v) => isRelationEntry(v) && !isMediaEntry(v));
  }
  return isRelationEntry(value) && !isMediaEntry(value);
}

/** Admin-only/private data (medical record numbers, consent-form uploads, contact details) — never fed to a prompt, never a relation target, regardless of relation-field shape. */
function isInternalField(field) {
  return field.endsWith('_internal');
}

// `condition.cost_calculator_leads` is a real, live example: a relation to
// prospective-patient contact/lead data, not editorial content. Whole
// content types this pattern would catch (cost-calculator-lead,
// contact-submission, …) are excluded further upstream, at registry
// generation time (see generate-relation-schema.js's EXCLUDED_API_IDS) —
// this regex is the remaining field-level safety net for text flattening.
const SENSITIVE_FIELD_NAME_RE = /lead|contact_form|submission|inquiry|enquiry/i;

/**
 * True only for "this plural route does not exist" (Strapi 404). Anything
 * else — no token configured, a 401/403, a network failure, a 500 — is a
 * systemic problem, not evidence the content type is absent, and must NOT be
 * swallowed the same way: a misconfigured token would otherwise make every
 * registered type look 404-like and discovery would silently report zero
 * content types, which reads as "this app has no content" instead of
 * "credentials are broken".
 */
function isNotFound(err) {
  return /Strapi API error \[404\]/.test(err.message || '');
}

/** One registry entry's live entry count, or null if its route no longer exists (the schema snapshot is stale for this type). Any other failure propagates. */
async function checkLive(registryEntry) {
  try {
    const res = await strapiRequest(`${API_BASE}/${registryEntry.plural}?pagination[pageSize]=1`);
    return res.meta?.pagination?.total ?? (res.data || []).length;
  } catch (e) {
    if (isNotFound(e)) return null;
    throw new Error(`checking "${registryEntry.plural}" failed: ${e.message}`);
  }
}

/**
 * Every registered content type with its live entry count, skipping any
 * whose route 404s (schema drift since the registry was generated).
 * Sequential, not parallel — this is a one-off, low-frequency call (a
 * manual "Discover" button), consistent with every other Strapi-fetching
 * loop in this app.
 */
async function discoverContentTypes() {
  const found = [];
  for (const registryEntry of REGISTRY.contentTypes) {
    const entryCount = await checkLive(registryEntry);
    if (entryCount === null) continue;
    found.push({
      apiId: registryEntry.apiId,
      plural: registryEntry.plural,
      label: registryEntry.displayName,
      entryCount,
      titleField: registryEntry.titleField,
      lastNameField: registryEntry.lastNameField,
      slugField: registryEntry.slugField,
      excerptField: registryEntry.excerptField,
      relationFields: registryEntry.relationFields
        .filter((rf) => !rf.private)
        .map((rf) => ({
          field: rf.field,
          cardinality: rf.cardinality,
          targetApiId: rf.targetApiId,
          reserved: RESERVED_RELATION_FIELDS.has(rf.field),
          nonContent: Boolean(rf.nonContent),
        })),
    });
  }
  return found;
}

/** A (contentType, field) pair is a legitimate Relations-tab WRITE target only if it's a real relation field, not reserved by another feature, and not editorial metadata (e.g. `author`). */
function isWritableRelationField(contentType, field) {
  const rf = (contentType.relationFields || []).find((r) => r.field === field);
  return Boolean(rf) && !rf.reserved && !rf.nonContent;
}

module.exports = {
  discoverContentTypes,
  isRelationValue,
  isWritableRelationField,
  isInternalField,
  RESERVED_RELATION_FIELDS,
  SENSITIVE_FIELD_NAME_RE,
  REGISTRY,
};
